### ISSUE TITLE
Console for version 6?

### ISSUE THREAD

**Issue by tommyw** [sitereactor/umbraco-console-example#3]
Hi,

You mention that there's a tag for the v6 verison, but I can't find it. Do you have this available still? I've created a console app for v6, but Umbraco.Core throws an exception when saving content, so was wondering if you v6 verison might have something else happening in the BootManager.

Thanks in advance,

Tom

**Comment by sitereactor** [comment]
Yes, there is a tag for the v6 version but I forgot to push it along with commits. Buts its the last commit in the gab before the v7 version is implemented. I'll try and get the tag pushed as well.

**Comment by sitereactor** [comment]
The tag for this (version 6 revision of the console app) revision should now have been pushed https://github.com/sitereactor/umbraco-console-example/commit/c7f2c2b0e6abdb2d822db261715237820e4f6e0a
