### ISSUE TITLE
Invalid column name 'alias'.

### ISSUE THREAD

**Issue by kid-cavaquinho** [sitereactor/umbraco-console-example#6]
When trying to add a node using ContentService an exception is thrown with 'Invalid column name 'alias'. Is it related with the cmsDocument table?

EDIT : But this is probably related with old references of umbraco? Going to change them and give it a try.

**Comment by antao** [comment]
But this is probably related with old references of umbraco? Going to change them and give it a try.

**Comment by kid-cavaquinho** [comment]
It is related with the current 7.0.2 core dlls, update them and everything runs smoothly again.
